const PROJECTS = [
	{
		title: "Coursera",
		work: "Full project",
		description: "Online kurslar savdosi uchun qilingan proyekt. Foydalanuvchi kurs qo'shib, uni sotishi(sayt valutasida) va undan kelgan pulga o'zi kurs sotib olishi mumkin. Bundan tashqari foydalanuvchi sotib olgan kursiga kommentariya qoldirishi, unga baho berishi(reyting) va o'zining kurslariga chegirma qo'yib sotishi mumkin(misol uchun bir kursga 25-maygacha 14%'li chegirma qoyishi mumkin)",
		lib: "Nest.js | TypeScript",
		database: "PostgreSQL",
		orm: "Typeorm",
		frontend: "Vue.js",
		other: ["Graphql"],
		github: "https://github.com/Javohir-Abdusattorov/Coursera",
		direct: null,
	},
	{
		title: "Litsey",
		work: "Full project",
		description: "Litsey uchun boshqaruv tizimi. Litsey davomati, guruh va talaba jurnallari, onlayn dars jarayonini o'z ichiga oladi. Va saytdan litsey rahbari(direktor), rahbar o'rinbosarlari(zauchlar), o'qituvchi va o'quvchi foyldalanishi kerak",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Html/Css/jQuery",
		other: ["MVC architecture", "Export to exel"],
		github: "https://github.com/Javohir-Abdusattorov/Litsey",
		direct: null,
	},
	{
		title: "Shoppers",
		work: "Backend",
		description: "E-commerce proyekt. AliExpress'ga funksional o'xshatib qilingan proyekt",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: null,
		other: ["MVC architecture"],
		github: "https://github.com/Javohir-Abdusattorov/Shoppers",
		direct: "https://shoppers.uz/",
	},
	{
		title: "Mathclub",
		work: "Full project",
		description: "Matematike bo'yicha online kurslar do'koni",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Html/Css/jQuery",
		other: ["Payme integration", "Video security"],
		github: "https://github.com/Javohir-Abdusattorov/Mathclub",
		direct: "http://mathclub.uz/",
	},
	{
		title: "Invan",
		work: "Backend",
		description: "E-commerce",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: null,
		other: ["MVC architecture", "Export to exel"],
		github: "https://github.com/Javohir-Abdusattorov/Invan",
		direct: null,
	},
	{
		title: "Live Chat",
		work: "Full project",
		description: "Realtime chat. Chat guruhlarda olib boriladi",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Html/Css/Websockets",
		other: ["Socket.io"],
		github: null,
		direct: "https://online-live-chat-main.herokuapp.com/",
	},
	{
		title: "Blog",
		work: "Full project",
		description: "Vue.js, Vuex, VueRouter orqali qilingan, asosan frontend'ga e'tibor qaratilgan blog proyekt",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Vue.js",
		other: ["Vuex", "VueRouter"],
		github: "https://github.com/Javohir-Abdusattorov/Blog",
		direct: null,
	},
]