const PROJECTS = [
	{
		title: "Coursera",
		work: "Full project",
		description: "Onlayn kurslar savdosi uchun platforma. Foydalanuvchilar o'zlarini kurslarini qo'shishi va boshqa foydalanuvchilar qo'shgan kurslarni sotib olishlari mumkin. Savdo sayt valyutasida qilinadi. Foydalanuvchilar o'z kurslariga chegirma qo'yishlari mumkin. Bunda kurs egasi chegirma foizini va chegirma qachon tugashini belgilaydi. Asosiy sahifada esa eng katta chegirma foizga ega kurs barcha foydalanuvchiga tavsiya qilinadi. Undan tashqari foydalanuvchi sotib olgan kurslariga kommentariya qoldirishi, unga baho berishi(reyting) mumkin.",
		lib: "Nest.js | TypeScript",
		database: "PostgreSQL",
		orm: "Typeorm",
		frontend: "Vue.js",
		other: ["Graphql"],
		github: "https://github.com/Javohir-Abdusattorov/Coursera",
		direct: null,
	},
	{
		title: "Litsey",
		work: "Full project",
		description: "Litseylar uchun boshqaruv tizimi. Boshqaruv tizim talabalar davomatini, talabalarning har bir fandan jurnalini, online ta'limni va talabalarning umumiy ma'lumotlarini o'z ichiga oladi. Tizimda bundan tashqari boshqa funksiyalar juda ko'p.",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Html/Css/jQuery",
		other: ["MVC architecture", "Export to exel"],
		github: "https://github.com/Javohir-Abdusattorov/Litsey",
		direct: null,
	},
	{
		title: "Shoppers",
		work: "Backend",
		description: "E-commerce sayt. Sayt tovarlarni online sotish bilan shug'ullanadi. Savdo AliExpress platformasiga o'xshab qilinadi: brendlar admin bilan kelishgan holda ro'yxatdan o'tkaziladi, va ular o'zini tovarlarini sotishni boshlaydi. Yetkazib berishni admin amalga oshiradi. Tovar xaridorga ma'qul kelmasa, u tovarni reytingini pasaytirishi, tovarni qaytarib yuborishi mumkin bo'ladi. Va brendning ham reytingi pasayadi bu bilan.",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: null,
		other: ["MVC architecture"],
		github: "https://github.com/Javohir-Abdusattorov/Shoppers",
		direct: "https://shoppers.uz/",
	},
	{
		title: "Mathclub",
		work: "Full project",
		description: "Matematika bo'yicha darslar sotuvi bilan shug'ullanadigan platforma. Darslar abituriyentlar va maktab o'quvchilari uchun yuklanadi. Darslar modul - mavzu - dars tartibida yuklanadi va birinchi 3ta mavzu barcha foydaluvchi uchun bepul bo'ladi. To'lov Payme orqali amalga oshiriladi",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Html/Css/jQuery",
		other: ["Payme integration", "Video security"],
		github: "https://github.com/Javohir-Abdusattorov/Mathclub",
		direct: "http://mathclub.uz/",
	},
	{
		title: "Invan",
		work: "Backend",
		description: "Tovar ishlab chiqaruvchilar uchun ichki tizim. Tizim tovarlarni nazorat qilish uchun tayyorlangan.",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: null,
		other: ["MVC architecture", "Export to exel"],
		github: "https://github.com/Javohir-Abdusattorov/Invan",
		direct: null,
	},
	{
		title: "Live Chat",
		work: "Full project",
		description: "Realtime chat. Chat guruhlarda olib boriladi",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Html/Css/Websockets",
		other: ["Socket.io"],
		github: null,
		direct: "https://online-live-chat-main.herokuapp.com/",
	},
	{
		title: "Blog",
		work: "Full project",
		description: "Vue.js, Vuex, VueRouter orqali qilingan, asosan frontend'ga e'tibor qaratilgan blog proyekt",
		lib: "Express.js | JavaScript",
		database: "MongoDB",
		orm: "Mongoose",
		frontend: "Vue.js",
		other: ["Vuex", "VueRouter"],
		github: "https://github.com/Javohir-Abdusattorov/Blog",
		direct: null,
	},
]